-- ==========================================
-- SKEMA DATABASE TRIFSHOP (SUPABASE POSTGRES)
-- Copy semua teks di bawah ini dan Paste di menu "SQL Editor" Supabase Anda, lalu klik "Run".
-- ==========================================

-- 1. Buat Tabel Kategori
CREATE TABLE IF NOT EXISTS categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT,
  description TEXT,
  image TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Buat Tabel Produk
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  price BIGINT NOT NULL,
  condition INTEGER NOT NULL CHECK (condition >= 1 AND condition <= 10),
  images TEXT[] NOT NULL,
  description TEXT,
  defect_description TEXT,
  seller_id UUID, -- Akan disambung ke tabel auth pengguna nantinya
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Buat Tabel Pesanan (Orders)
CREATE TABLE IF NOT EXISTS orders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID, -- Pembeli
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  total_price BIGINT NOT NULL,
  payment_method TEXT NOT NULL,
  shipping_address TEXT NOT NULL,
  status TEXT DEFAULT 'PENDING_PAYMENT' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Mengizinkan pembacaan publik untuk kategori dan produk (Public Read Access)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-only access to categories" ON categories FOR SELECT USING (true);
CREATE POLICY "Allow public read-only access to products" ON products FOR SELECT USING (true);

-- (Opsional) Masukkan 1 Data Kategori Dummy untuk Tes
INSERT INTO categories (id, name, icon, description, image) 
VALUES ('pakaian-pria', 'Pakaian Pria', '👔', 'Pakaian pria preloved berkualitas', '/images/cat_pakaian_pria.png')
ON CONFLICT (id) DO NOTHING;

-- (Opsional) Masukkan 1 Data Produk Dummy untuk Tes
INSERT INTO products (slug, title, price, condition, images, description, defect_description)
VALUES ('pakaian-pria', 'Jaket Denim Vintage (Tes Database)', 150000, 8, ARRAY['https://images.unsplash.com/photo-1576871337622-98d48d1cf531?auto=format&fit=crop&q=80&w=400'], 'Jaket keren dari Supabase', 'Tidak ada cacat')
ON CONFLICT DO NOTHING;
